# Generated by Django 3.1.3 on 2021-05-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbclc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
