# Generated by Django 3.1.3 on 2021-05-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbclc', '0004_auto_20210518_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='name',
        ),
    ]
