# Generated by Django 3.1.3 on 2021-05-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbclc', '0006_auto_20210518_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineCongestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=10)),
                ('congestion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StopCongestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c0', models.PositiveIntegerField()),
                ('c1', models.PositiveIntegerField()),
                ('c2', models.PositiveIntegerField()),
                ('c3', models.PositiveIntegerField()),
                ('c4', models.PositiveIntegerField()),
                ('c5', models.PositiveIntegerField()),
                ('c6', models.PositiveIntegerField()),
                ('c7', models.PositiveIntegerField()),
                ('c8', models.PositiveIntegerField()),
                ('c9', models.PositiveIntegerField()),
                ('c10', models.PositiveIntegerField()),
                ('c11', models.PositiveIntegerField()),
                ('c12', models.PositiveIntegerField()),
                ('c13', models.PositiveIntegerField()),
                ('c14', models.PositiveIntegerField()),
                ('c15', models.PositiveIntegerField()),
                ('c16', models.PositiveIntegerField()),
                ('c17', models.PositiveIntegerField()),
                ('c18', models.PositiveIntegerField()),
                ('c19', models.PositiveIntegerField()),
                ('c20', models.PositiveIntegerField()),
                ('c21', models.PositiveIntegerField()),
                ('c22', models.PositiveIntegerField()),
                ('c23', models.PositiveIntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbclc.stop')),
            ],
        ),
    ]
